# Generated by Django 2.2 on 2020-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200820_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='login',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
